baseURL = "https://www.inisenergy.com/insights/"
languageCode = "en-ie"
title = "Irish Energy Markets"
theme = "congo"

[pagination]
  pagerSize = 10

[permalinks]
  daily = "/daily/:year/:month/:day/"
  weekly = "/weekly/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^VERCEL_']
